### ISSUE TITLE
Design How-it-work page

### ISSUE THREAD

**Issue by diafygi** [open-austin/vax-codes#5]

**Comment by lalver1** [comment]
Hi Daniel, I think I'll be able to get help to make some graphics for the How it Works Page but I wanted to see if these steps are correct (and if there's too much or not enough detail) before starting to work on the graphics:

1. An approved health organization that can confirm if someone has received the COVID-19 vaccine becomes a Vax.Codes QR code issuer. (Picture of health buildings issuing QR codes)
2. When the person gets the COVID-19 vaccine, they receive both a COVID-19 vaccine card and a Vax.Codes QR code (printed or electronic) from the approved health organization. (Picture of a person looking at both items, the QR code may be electronic)
3. The person shows up to an event requiring proof of COVID-19 vaccination and shows their QR code to the event organizer. (Picture at the door showing code)
4. Scanning the QR code will open a URL with the person's name, birth date, and verification that they have received a COVID-19 vaccine. (Picture of a screenshot of the /scan page)
5. The event organizer checks the name and birth date on the verification against the person's ID. If the person's ID matches, they are allowed into the event. (Picture of the person with a green check mark, something like 'good to go')

Also, I may change 'the person' to 'you', it probably makes it more clear.

**Comment by diafygi** [comment]
Added placeholder content for now until we get the illustrations in place.

**Comment by diafygi** [comment]
Merged #22 thanks @lalver1 !
